### ISSUE TITLE
Fails to build on Raspberry Pi OS without src modification

### ISSUE THREAD

**Issue by m-roberts** [NICHOLAS85/gebaar-libinput#11]
I needed to comment out the following lines for this to compile:

https://github.com/NICHOLAS85/gebaar-libinput/blob/c25c74b6e35dda68703b2a40aaaff98ba614d2c6/src/io/input.cpp#L811-L812

Not sure why, but should be easily reproduced on Raspberry Pi OS.

**Comment by NICHOLAS85** [comment]
Try out the latest commit! I've removed the unused events so hopefully, it'll compile without error. Additionally what version of libinput do you have installed?
